In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
archivo='../Documentos/Meta.csv'
df=pd.read_csv(archivo)
df

,Proyecto,Tipo,Capacidad,Departamento,Municipio,Código Departamento,Código Municipio,Fecha estimada FPO,Energía [kWh/día],Usuarios,Inversión estimada [COP],Empleos estimados,Emisiones CO2 [Ton/año]
0,JEPIRACHI,Eólico,18.42,LA GUAJIRA,URIBIA,44,44847,2004-04-27T00:00:00.000,"176,832","30,665","79,206,000,000",51,"51,635"
1,AUTOG CELSIA SOLAR YUMBO,Solar,9.80,VALLE DEL CAUCA,YUMBO,76,76892,2017-03-09T00:00:00.000,"47,040","8,157","42,140,000,000",68,"13,736"
2,CELSIA SOLAR BOLIVAR,Solar,8.06,BOLÍVAR,SANTA ROSA,13,13683,2019-02-01T00:00:00.000,"38,688","6,709","34,658,000,000",56,"11,297"
3,EL PASO SOLAR (ENEL GREEN POWER),Solar,67.00,CESAR,EL PASO,20,20250,2019-04-05T00:00:00.000,"321,600","55,769","288,100,000,000",466,"93,907"
4,SOLAR CASTILLA ECP,Solar,20.00,META,CASTILLA LA NUEVA,50,50150,2019-10-10T00:00:00.000,"96,000","16,647","86,000,000,000",139,"28,032"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,BUGA 1 PARTE 2,Solar,5.94,VALLE DEL CAUCA,"""""",76,76,2022-12-31T00:00:00.000,"28,512","4,944","22,275,000,000",41,"8,326"
154,BUGA 1 PARTE 1,Solar,3.96,VALLE DEL CAUCA,"""""",76,76,2022-07-31T00:00:00.000,"19,008","3,296","14,850,000,000",28,"5,550"
155,REFINERÍA GRB,Solar,21.00,SANTANDER,BARRANCABERMEJA,68,68081,2023-12-31T00:00:00.000,"100,800","17,480","78,750,000,000",146,"29,434"
156,EMSA GD Y AG (34 Proyectos),Solar,1.90,META,VILLAVICENCIO,50,50001,2022-05-31T00:00:00.000,"9,120","1,582","8,170,000,000",13,"2,663"
157,ENELAR GD Y AG (4 Proyectos),Solar,0.11,ARAUCA,ARAUCA,81,81001,2022-05-31T00:00:00.000,528,92,"473,000,000",1,154

## Revisión general de la bd META

In [ ]:
df.info() # => Se observa que no hay valores nulos, pero si inconsisctencias en el tipo de datos

<class 'pandas.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Proyecto                  158 non-null    str
 1   Tipo                      158 non-null    str
 2   Capacidad                 158 non-null    float64
 3   Departamento              158 non-null    str
 4   Municipio                 158 non-null    str
 5   Código Departamento       158 non-null    int64
 6   Código Municipio          158 non-null    int64
 7   Fecha estimada FPO        158 non-null    str
 8   Energía [kWh/día]         158 non-null    str
 9   Usuarios                  158 non-null    str
 10  Inversión estimada [COP]  158 non-null    str
 11  Empleos estimados         158 non-null    str
 12  Emisiones CO2 [Ton/año]   158 non-null    str
dtypes: float64(1), int64(2), str(10)
memory usage: 31.5 KB

In [ ]:
# Cuenta los registros y lo convierte en una tabla organizada
resumen_tipos = df['Tipo'].value_counts().reset_index()

# Le cambiamos el nombre a las columnas para que sea más claro
resumen_tipos.columns = ['Tipo de Proyecto', 'Cantidad de Registros']

# Mostramos el resultado
print(resumen_tipos)

  Tipo de Proyecto  Cantidad de Registros
0            Solar                    145
1           Eólico                     13

## LIMPIEZA DE DATOS

1. Valores nulos o faltantes: Identificación y tratamiento de datos ausentes (NaN, None, celdas vacías).

In [ ]:
# Ver valores nulos por columna => Se corrobora que no hay valores nulos
df.isnull().sum() #es equivalente a df.isna().sum()

Proyecto                    0
Tipo                        0
Capacidad                   0
Departamento                0
Municipio                   0
Código Departamento         0
Código Municipio            0
Fecha estimada FPO          0
Energía [kWh/día]           0
Usuarios                    0
Inversión estimada [COP]    0
Empleos estimados           0
Emisiones CO2 [Ton/año]     0
dtype: int64

2. Duplicados: Buscar y eliminar si hay registros duplicados.

In [ ]:
# Verificar duplicados => Se corrobora que hay 2 registros duplicados
duplicados = df.duplicated().sum()
print(f"Filas duplicadas: {duplicados}")

Filas duplicadas: 2

In [ ]:
# Se revisa el contenido de los registros duplicados
df[df.duplicated(keep=False)]

,Proyecto,Tipo,Capacidad,Departamento,Municipio,Código Departamento,Código Municipio,Fecha estimada FPO,Energía [kWh/día],Usuarios,Inversión estimada [COP],Empleos estimados,Emisiones CO2 [Ton/año]
100,DULIMA PARTE 2,Solar,13.93,TOLIMA,FLANDES,73,73275,2023-01-16T00:00:00.000,"66,864","11,595","52,237,500,000",97,"19,524"
101,"PARQUE SOLAR LA VICTORIA 1 Y 2 (2X19,9) PARTE 2",Solar,21.89,VALLE DEL CAUCA,ZARZAL,76,76895,2023-04-25T00:00:00.000,"105,072","18,221","82,087,500,000",152,"30,681"
102,DULIMA PARTE 2,Solar,13.93,TOLIMA,FLANDES,73,73275,2023-01-16T00:00:00.000,"66,864","11,595","52,237,500,000",97,"19,524"
104,"PARQUE SOLAR LA VICTORIA 1 Y 2 (2X19,9) PARTE 2",Solar,21.89,VALLE DEL CAUCA,ZARZAL,76,76895,2023-04-25T00:00:00.000,"105,072","18,221","82,087,500,000",152,"30,681"

In [ ]:
# Se eliminan duplicados en una nueva variable para conservar el original
df1 = df.drop_duplicates()
# Se corrobora que no quedaron registros duplicados
df1[df1.duplicated(keep=False)]

Empty DataFrame
Columns: [Proyecto, Tipo, Capacidad, Departamento, Municipio, Código Departamento, Código Municipio, Fecha estimada FPO, Energía [kWh/día], Usuarios, Inversión estimada [COP], Empleos estimados, Emisiones CO2 [Ton/año]]
Index: []

3. Inconsistencias de formato (Unificar formatos de fechas, números, mayúsculas/minúsculas) y Conversión de tipos de datos (Asegurar que cada columna tenga el tipo de dato correcto)

In [14]:
# Unificar texto a capitalizados (la primera letra de cada palabra en mayúscula)
# para las columnas de texto: Proyecto,Tipo,Departamento,Municipio
df1['Proyecto'] = df1['Proyecto'].str.capitalize()
df1['Tipo'] = df1['Tipo'].str.capitalize()
df1['Departamento'] = df1['Departamento'].str.capitalize()
df1['Municipio'] = df1['Municipio'].str.capitalize()
df1

,Proyecto,Tipo,Capacidad,Departamento,Municipio,Código Departamento,Código Municipio,Fecha estimada FPO,Energía [kWh/día],Usuarios,Inversión estimada [COP],Empleos estimados,Emisiones CO2 [Ton/año]
0,Jepirachi,Eólico,18.42,La guajira,Uribia,44,44847,2004-04-27T00:00:00.000,"176,832","30,665","79,206,000,000",51,"51,635"
1,Autog celsia solar yumbo,Solar,9.80,Valle del cauca,Yumbo,76,76892,2017-03-09T00:00:00.000,"47,040","8,157","42,140,000,000",68,"13,736"
2,Celsia solar bolivar,Solar,8.06,Bolívar,Santa rosa,13,13683,2019-02-01T00:00:00.000,"38,688","6,709","34,658,000,000",56,"11,297"
3,El paso solar (enel green power),Solar,67.00,Cesar,El paso,20,20250,2019-04-05T00:00:00.000,"321,600","55,769","288,100,000,000",466,"93,907"
4,Solar castilla ecp,Solar,20.00,Meta,Castilla la nueva,50,50150,2019-10-10T00:00:00.000,"96,000","16,647","86,000,000,000",139,"28,032"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Buga 1 parte 2,Solar,5.94,Valle del cauca,"""""",76,76,2022-12-31T00:00:00.000,"28,512","4,944","22,275,000,000",41,"8,326"
154,Buga 1 parte 1,Solar,3.96,Valle del cauca,"""""",76,76,2022-07-31T00:00:00.000,"19,008","3,296","14,850,000,000",28,"5,550"
155,Refinería grb,Solar,21.00,Santander,Barrancabermeja,68,68081,2023-12-31T00:00:00.000,"100,800","17,480","78,750,000,000",146,"29,434"
156,Emsa gd y ag (34 proyectos),Solar,1.90,Meta,Villavicencio,50,50001,2022-05-31T00:00:00.000,"9,120","1,582","8,170,000,000",13,"2,663"
157,Enelar gd y ag (4 proyectos),Solar,0.11,Arauca,Arauca,81,81001,2022-05-31T00:00:00.000,528,92,"473,000,000",1,154

In [16]:
# Unificar formato de fechas
df1['Fecha estimada FPO'] = pd.to_datetime(df1['Fecha estimada FPO'], errors='coerce') 
df1 # Ajusta el nombre de la columna

,Proyecto,Tipo,Capacidad,Departamento,Municipio,Código Departamento,Código Municipio,Fecha estimada FPO,Energía [kWh/día],Usuarios,Inversión estimada [COP],Empleos estimados,Emisiones CO2 [Ton/año]
0,Jepirachi,Eólico,18.42,La guajira,Uribia,44,44847,2004-04-27,"176,832","30,665","79,206,000,000",51,"51,635"
1,Autog celsia solar yumbo,Solar,9.80,Valle del cauca,Yumbo,76,76892,2017-03-09,"47,040","8,157","42,140,000,000",68,"13,736"
2,Celsia solar bolivar,Solar,8.06,Bolívar,Santa rosa,13,13683,2019-02-01,"38,688","6,709","34,658,000,000",56,"11,297"
3,El paso solar (enel green power),Solar,67.00,Cesar,El paso,20,20250,2019-04-05,"321,600","55,769","288,100,000,000",466,"93,907"
4,Solar castilla ecp,Solar,20.00,Meta,Castilla la nueva,50,50150,2019-10-10,"96,000","16,647","86,000,000,000",139,"28,032"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Buga 1 parte 2,Solar,5.94,Valle del cauca,"""""",76,76,2022-12-31,"28,512","4,944","22,275,000,000",41,"8,326"
154,Buga 1 parte 1,Solar,3.96,Valle del cauca,"""""",76,76,2022-07-31,"19,008","3,296","14,850,000,000",28,"5,550"
155,Refinería grb,Solar,21.00,Santander,Barrancabermeja,68,68081,2023-12-31,"100,800","17,480","78,750,000,000",146,"29,434"
156,Emsa gd y ag (34 proyectos),Solar,1.90,Meta,Villavicencio,50,50001,2022-05-31,"9,120","1,582","8,170,000,000",13,"2,663"
157,Enelar gd y ag (4 proyectos),Solar,0.11,Arauca,Arauca,81,81001,2022-05-31,528,92,"473,000,000",1,154

In [ ]:
#Revisar los datos registrados en columnas numéricas
df1['Empleos estimados'].unique()

<ArrowStringArray>
[   '51',    '68',    '56',   '466',   '139',     '1',     '0',    '69',
     '2',    '21',    '10',     '4',    '12',    '16',     '6',    '15',
     '7',    '46',    '32',    '35',     '9',   '166',    '58',    '72',
    '17',    '84',   '425',    '13',    '70',     '8',    '55', '1,183',
   '125',   '626',   '689',   '134',    '42',   '695',    '33',    '60',
   '181',    '97',   '751',   '589',    '41',    '48',   '152',   '133',
   '606',   '416',   '835', '1,392',    '26',    '29',    '28',    '24',
    '38',   '542',   '313',   '490',   '209',   '557',   '696', '4,872',
   '693',   '348',   '578', '1,114',   '275', '1,253',   '222',   '550',
   '244',    '93',   '146']
Length: 75, dtype: str

In [23]:
#convertir a numérico, forzando errores a NaN para identificar problemas de formato
#df1["Empleos estimados"] = pd.to_numeric(df1["Empleos estimados"], errors="coerce")
try:
    df1["Empleos estimados"] = (
        df1["Empleos estimados"]
        .str.replace(',', '')
        .str.strip()
        .pipe(pd.to_numeric, errors='coerce')
    )
except Exception as e:
    pass

In [ ]:
#comprobar que se hizo la conversión correctamente
df1['Empleos estimados'].unique()

array([  51,   68,   56,  466,  139,    1,    0,   69,    2,   21,   10,
          4,   12,   16,    6,   15,    7,   46,   32,   35,    9,  166,
         58,   72,   17,   84,  425,   13,   70,    8,   55, 1183,  125,
        626,  689,  134,   42,  695,   33,   60,  181,   97,  751,  589,
         41,   48,  152,  133,  606,  416,  835, 1392,   26,   29,   28,
         24,   38,  542,  313,  490,  209,  557,  696, 4872,  693,  348,
        578, 1114,  275, 1253,  222,  550,  244,   93,  146])

In [24]:
#Revisar los datos registrados en columnas numéricas
df1['Usuarios'].unique()

<ArrowStringArray>
[ '30,665',   '8,157',   '6,709',  '55,769',  '16,647',      '83',       '8',
      '75',   '8,240',      '67',
 ...
 '164,560', '149,827', '329,236', '416,185',  '29,133',  '11,071',   '3,296',
  '17,480',   '1,582',      '92']
Length: 106, dtype: str

In [ ]:
#convertir a numérico, forzando errores a NaN para identificar problemas de formato
try:
    df1["Usuarios"] = (
        df1["Usuarios"]
        .str.replace(',', '')
        .str.strip()
        .pipe(pd.to_numeric, errors='coerce')
    )
except Exception as e:
    pass

In [26]:
#Comprobar que se hizo la conversión correctamente
df1['Usuarios'].unique()

array([ 30665,   8157,   6709,  55769,  16647,     83,      8,     75,
         8240,     67,    208,    166,    125,  16564,   2497,   1249,
          499,    458,    191,    175,     33,     25,   1165,   1448,
         1873,    724,    142,   1831,    832,   5444,   3779,   4212,
           50,   8182,   1099,  19910,   6975,   8557,   1989,   1049,
        10072,  50775,   1540,   1498,    250,   8340,    941,   1956,
        33128, 141503,      4,  14899,  74913,  82405,  16065,   5077,
        83154,  19977,   7158,  21642,   4994,  11653, 449480, 352925,
         4944,   5768,  11595,  18221,   4969,  14908,  15890,  72416,
        49692,  99884, 166474,   3071,   3513,   3329,    782,   2913,
         3454,    508,   4578,   1082, 324674,  37457, 293494, 124855,
        66590,  83237, 582659,  82821,  41618,  16481,  69087, 133179,
       164560, 149827, 329236, 416185,  29133,  11071,   3296,  17480,
         1582,     92])

In [27]:
#Revisar los datos registrados en columnas numéricas
df1['Energía [kWh/día]'].unique()

<ArrowStringArray>
[  '176,832',    '47,040',    '38,688',   '321,600',    '96,000',       '480',
        '48',       '432',    '47,520',       '384',
 ...
   '948,960',   '864,000', '1,898,592', '2,400,000',   '168,000',    '63,840',
    '19,008',   '100,800',     '9,120',       '528']
Length: 106, dtype: str

In [30]:
#convertir a numérico, forzando errores a NaN para identificar problemas de formato
try:
    df1["Energía [kWh/día]"] = (
        df1["Energía [kWh/día]"]
        .str.replace(',', '')
        .str.strip()
        .pipe(pd.to_numeric, errors='coerce')
    )
except Exception as e:
    pass

In [31]:
#Comprobar el cambio de tipo de dato
df1['Energía [kWh/día]'].unique()

array([ 176832,   47040,   38688,  321600,   96000,     480,      48,
           432,   47520,     384,    1200,     960,     720,   95520,
         14400,    7200,    2880,    2640,    1104,    1008,     192,
           144,    6720,    8352,   10800,    4176,     816,   10560,
          4800,   31392,   21792,   24288,     288,   47184,    6336,
        114816,   40224,   49344,   11472,    6048,   58080,  292800,
          8880,    8640,    1440,   48096,    5424,   11280,  191040,
        816000,      21,   85920,  432000,  475200,   92640,   29280,
        479520,  115200,   41280,  124800,   28800,   67200, 2592000,
       2035200,   28512,   33264,   66864,  105072,   28656,   85968,
         91632,  417600,  286560,  576000,  960000,   17712,   20256,
         19200,    4512,   16800,   19920,    2928,   26400,    6240,
       1872288,  216000, 1692480,  720000,  384000,  480000, 3360000,
        477600,  240000,   95040,  398400,  768000,  948960,  864000,
       1898592, 2400000,  168000,   63840,   19008,  100800,    9120,
           528])

In [28]:
#Revisar los datos registrados en columnas numéricas
df1['Inversión estimada [COP]'].unique()

<ArrowStringArray>
[ '79,206,000,000',  '42,140,000,000',  '34,658,000,000', '288,100,000,000',
  '86,000,000,000',     '430,000,000',      '43,000,000',     '387,000,000',
  '42,570,000,000',     '344,000,000',
 ...
 '675,000,000,000', '300,000,000,000', '741,638,000,000', '937,500,000,000',
 '131,250,000,000',  '57,190,000,000',  '14,850,000,000',  '78,750,000,000',
   '8,170,000,000',     '473,000,000']
Length: 112, dtype: str

In [32]:
#convertir a numérico, forzando errores a NaN para identificar problemas de formato
#df1["Empleos estimados"] = pd.to_numeric(df1["Empleos estimados"], errors="coerce")
try:
    df1["Inversión estimada [COP]"] = (
        df1["Inversión estimada [COP]"]
        .str.replace(',', '')
        .str.strip()
        .pipe(pd.to_numeric, errors='coerce')
    )
except Exception as e:
    pass

In [33]:
#Comprobar el cambio de tipo de dato
df1['Inversión estimada [COP]'].unique()

array([  79206000000,   42140000000,   34658000000,  288100000000,
         86000000000,     430000000,      43000000,     387000000,
         42570000000,     344000000,    1075000000,     860000000,
           645000000,   85570000000,   12900000000,    6450000000,
          2580000000,    2365000000,     989000000,     903000000,
           172000000,     129000000,    6020000000,    7482000000,
          9675000000,    3741000000,     731000000,    9460000000,
          4300000000,   28122000000,   19522000000,   21758000000,
           258000000,   42269000000,    5676000000,  102856000000,
         36034000000,   44204000000,   10277000000,    5418000000,
         52030000000,  262300000000,    7955000000,    7740000000,
          1290000000,   43086000000,    4859000000,   10105000000,
        731000000000,    5160000000,   76970000000,   74625000000,
         37125000000,  337500000000,       9800000,  371250000000,
         72375000000,   22875000000,  374625000000,   51600000000,
         32250000000,   97500000000,   22500000000,   52500000000,
       1012500000000,  795000000000,   22275000000,   25987500000,
         52237500000,   82087500000,   22387500000,   67162500000,
         71587500000,  326250000000,  223875000000,  450000000000,
        750000000000,   13837500000,   15825000000,   15000000000,
          3525000000,     375000000,    6750000000,   13125000000,
         15562500000,    2287500000,    1125000000,   20625000000,
          4875000000,  731363000000,  168750000000,  661125000000,
        281250000000,  344000000000,  375000000000, 2625000000000,
        373125000000,    5625000000,  187500000000,  311250000000,
        600000000000,  370688000000,  675000000000,  300000000000,
        741638000000,  937500000000,  131250000000,   57190000000,
         14850000000,   78750000000,    8170000000,     473000000])

In [29]:
#Revisar los datos registrados en columnas numéricas
df1['Emisiones CO2 [Ton/año]'].unique()

<ArrowStringArray>
[ '51,635',  '13,736',  '11,297',  '93,907',  '28,032',     '140',      '14',
     '126',  '13,876',     '112',
 ...
 '277,096', '252,288', '554,389', '700,800',  '49,056',  '18,641',   '5,550',
  '29,434',   '2,663',     '154']
Length: 106, dtype: str

In [34]:
#convertir a numérico, forzando errores a NaN para identificar problemas de formato
#df1["Empleos estimados"] = pd.to_numeric(df1["Empleos estimados"], errors="coerce")
try:
    df1["Emisiones CO2 [Ton/año]"] = (
        df1["Emisiones CO2 [Ton/año]"]
        .str.replace(',', '')
        .str.strip()
        .pipe(pd.to_numeric, errors='coerce')
    )
except Exception as e:
    pass

In [ ]:
#Comprobar el cambio de tipo de dato
df1['Emisiones CO2 [Ton/año]'].unique()

array([ 51635,  13736,  11297,  93907,  28032,    140,     14,    126,
        13876,    112,    350,    280,    210,  27892,   4205,   2102,
          841,    771,    322,    294,     56,     42,   1962,   2439,
         3154,   1219,    238,   3084,   1402,   9166,   6363,   7092,
           84,  13778,   1850,  33526,  11745,  14408,   3350,   1766,
        16959,  85498,   2593,   2523,    420,  14044,   1584,   3294,
        55784, 238272,      6,  25089, 126144, 138758,  27051,   8550,
       140020,  33638,  12054,  36442,   8410,  19622, 756864, 594278,
         8326,   9713,  19524,  30681,   8368,  25103,  26757, 121939,
        83676, 168192, 280320,   5172,   5915,   5606,   1318,   4906,
         5817,    855,   7709,   1822, 546708,  63072, 494204, 210240,
       112128, 140160, 981120, 139459,  70080,  27752, 116333, 224256,
       277096, 252288, 554389, 700800,  49056,  18641,   5550,  29434,
         2663,    154])

In [36]:
#verificar los cambios realizados
df1.info()

<class 'pandas.DataFrame'>
Index: 156 entries, 0 to 157
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Proyecto                  156 non-null    str
 1   Tipo                      156 non-null    str
 2   Capacidad                 156 non-null    float64
 3   Departamento              156 non-null    str
 4   Municipio                 156 non-null    str
 5   Código Departamento       156 non-null    int64
 6   Código Municipio          156 non-null    int64
 7   Fecha estimada FPO        156 non-null    datetime64[us]
 8   Energía [kWh/día]         156 non-null    int64
 9   Usuarios                  156 non-null    int64
 10  Inversión estimada [COP]  156 non-null    int64
 11  Empleos estimados         156 non-null    int64
 12  Emisiones CO2 [Ton/año]   156 non-null    int64
dtypes: datetime64[us](1), float64(1), int64(7), str(4)
memory usage: 23.8 KB

In [38]:
#cambio de tipo de dato para inversión, energia y emisiones a float
try:
    df1["Inversión estimada [COP]"] = df1["Inversión estimada [COP]"].astype(float)
    df1["Energía [kWh/día]"] = df1["Energía [kWh/día]"].astype(float)
    df1["Emisiones CO2 [Ton/año]"] = df1["Emisiones CO2 [Ton/año]"].astype(float)
except ValueError as e:
    pass

In [39]:
#Se corrobora el cambio de tipo de dato a float para las columnas de inversión, energía y emisiones
df1.info()

<class 'pandas.DataFrame'>
Index: 156 entries, 0 to 157
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Proyecto                  156 non-null    str
 1   Tipo                      156 non-null    str
 2   Capacidad                 156 non-null    float64
 3   Departamento              156 non-null    str
 4   Municipio                 156 non-null    str
 5   Código Departamento       156 non-null    int64
 6   Código Municipio          156 non-null    int64
 7   Fecha estimada FPO        156 non-null    datetime64[us]
 8   Energía [kWh/día]         156 non-null    float64
 9   Usuarios                  156 non-null    int64
 10  Inversión estimada [COP]  156 non-null    float64
 11  Empleos estimados         156 non-null    int64
 12  Emisiones CO2 [Ton/año]   156 non-null    float64
dtypes: datetime64[us](1), float64(4), int64(4), str(4)
memory usage: 23.8 KB

4. Errores tipográficos: Corregir errores de escritura en nombres, categorías, etc.

In [ ]:
#Revisar los datos registrados en columnas tipo texto => Se confirma que no hay inconsistencias en los nombres de los proyectos
df1['Proyecto'].unique()

<ArrowStringArray>
[                            'Jepirachi',
              'Autog celsia solar yumbo',
                  'Celsia solar bolivar',
      'El paso solar (enel green power)',
                    'Solar castilla ecp',
       'Agpe tecnoempaques de occidente',
                  'Radar fac san andrés',
            'Agpe sfv mcdonalds soledad',
                  'Celsia solar espinal',
      'Federación nacional de cafeteros',
 ...
                          'Pubenza psr2',
                           'Sabanalarga',
   'Parque solar fotovoltaico fundación',
                                 'Tuluá',
 'Parque fotovoltaico montelíbano solar',
                        'Buga 1 parte 2',
                        'Buga 1 parte 1',
                         'Refinería grb',
           'Emsa gd y ag (34 proyectos)',
          'Enelar gd y ag (4 proyectos)']
Length: 156, dtype: str

In [ ]:
#Revisar los datos registrados en columnas tipo texto => Se confirma que no hay inconsistencias en los nombres de los tipos de proyectos
df1['Tipo'].unique()

<ArrowStringArray>
['Eólico', 'Solar']
Length: 2, dtype: str

In [ ]:
#Revisar los datos registrados en columnas tipo texto => Se confirma que no hay inconsistencias en los nombres de los departamentos
df1['Departamento'].unique()

<ArrowStringArray>
[                                              'La guajira',
                                          'Valle del cauca',
                                                  'Bolívar',
                                                    'Cesar',
                                                     'Meta',
 'Archipiélago de san andrés, providencia y santa catalina',
                                                'Atlántico',
                                                   'Tolima',
                                                'Antioquia',
                                                    'Chocó',
                                                'Risaralda',
                                                  'Córdoba',
                                                  'Guainía',
                                                'Santander',
                                                   'Caldas',
                                                    'Huila',
                                                   'Arauca',
                                                   'Boyacá',
                                              'Bogotá d.c.',
                                       'Norte de santander',
                                                 'Casanare',
                                                    'Sucre',
                                                    'Cauca',
                                                  'Quindío',
                                                'Magdalena',
                                             'Cundinamarca']
Length: 26, dtype: str

In [ ]:
#Revisar los datos registrados en columnas tipo texto => Se confirma que no hay inconsistencias en los nombres de los municipios
df1['Municipio'].unique()

<ArrowStringArray>
[                    'Uribia',                      'Yumbo',
                 'Santa rosa',                    'El paso',
          'Castilla la nueva',                       'Cali',
                 'San andrés',                    'Soledad',
                    'Espinal',                     'Ibagué',
                   'Medellín',                     'Unguía',
              'Puerto gaitán',        'Cartagena de indias',
                    'Pereira',               'Planeta rica',
                 'Candelaria',                   'Rionegro',
                    'Inírida',            'Barrancabermeja',
                  'Manizales',                      'Neiva',
                     'Arauca',                   'Montería',
                      'Tunja',                'Bogotá d.c.',
         'San josé de cúcuta',                      'Yopal',
               'Barranquilla',                     'Zarzal',
            'San benito abad',                     'Galapa',
                    'Popayán',                    'Armenia',
              'Villavicencio',                  'La dorada',
                 'Villanueva',                     'Armero',
 'San sebastián de mariquita',                      'Chinú',
          'San luis de sincé',                    'Cartago',
              'Zona bananera',                    'Baranoa',
                  'Polonuevo',                     'Arjona',
                    'Ciénaga',                    'Yaguará',
                 'Cantagallo',                     'Maicao',
                     'Melgar',                  'Andalucía',
                    'Malambo',                     'Manatí',
      'San josé de toluviejo',                    'Flandes',
              'Puerto tejada',                 'Los santos',
                    'Guaduas',                'Sabanalarga',
                  'Girardota',                     'Suesca',
                       'Sopó',                     'Madrid',
                     'Soacha',                   'Sesquilé',
                    'Ginebra',                'Piedecuesta',
                  'Aguachica',                  'La gloria',
               'La esperanza',                 'Chiriguaná',
                  'Cimitarra',                         '""',
             'Santa catalina',                'Puerto nare',
                   'Alvarado',                  'Fundación',
                      'Tuluá']
Length: 79, dtype: str

5. Homogeneidad de unidades: Unificar unidades de medida (dias vs años).

In [45]:
# Se crea Energía [kWh/año] a partir de Energía [kWh/día]
df1["Energía [kWh/año]"] = df1["Energía [kWh/día]"] * 365
df1

,Proyecto,Tipo,Capacidad,Departamento,Municipio,Código Departamento,Código Municipio,Fecha estimada FPO,Energía [kWh/día],Usuarios,Inversión estimada [COP],Empleos estimados,Emisiones CO2 [Ton/año],Energía [kWh/año]
0,Jepirachi,Eólico,18.42,La guajira,Uribia,44,44847,2004-04-27,176832.0,30665,7.920600e+10,51,51635.0,64543680.0
1,Autog celsia solar yumbo,Solar,9.80,Valle del cauca,Yumbo,76,76892,2017-03-09,47040.0,8157,4.214000e+10,68,13736.0,17169600.0
2,Celsia solar bolivar,Solar,8.06,Bolívar,Santa rosa,13,13683,2019-02-01,38688.0,6709,3.465800e+10,56,11297.0,14121120.0
3,El paso solar (enel green power),Solar,67.00,Cesar,El paso,20,20250,2019-04-05,321600.0,55769,2.881000e+11,466,93907.0,117384000.0
4,Solar castilla ecp,Solar,20.00,Meta,Castilla la nueva,50,50150,2019-10-10,96000.0,16647,8.600000e+10,139,28032.0,35040000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Buga 1 parte 2,Solar,5.94,Valle del cauca,"""""",76,76,2022-12-31,28512.0,4944,2.227500e+10,41,8326.0,10406880.0
154,Buga 1 parte 1,Solar,3.96,Valle del cauca,"""""",76,76,2022-07-31,19008.0,3296,1.485000e+10,28,5550.0,6937920.0
155,Refinería grb,Solar,21.00,Santander,Barrancabermeja,68,68081,2023-12-31,100800.0,17480,7.875000e+10,146,29434.0,36792000.0
156,Emsa gd y ag (34 proyectos),Solar,1.90,Meta,Villavicencio,50,50001,2022-05-31,9120.0,1582,8.170000e+09,13,2663.0,3328800.0
157,Enelar gd y ag (4 proyectos),Solar,0.11,Arauca,Arauca,81,81001,2022-05-31,528.0,92,4.730000e+08,1,154.0,192720.0

In [46]:
# Se crea  [kWh/año] a partir de Energía [kWh/día]
df1["Emisiones CO2 [Ton/días]"] = df1["Emisiones CO2 [Ton/año]"] / 365
df1

,Proyecto,Tipo,Capacidad,Departamento,Municipio,Código Departamento,Código Municipio,Fecha estimada FPO,Energía [kWh/día],Usuarios,Inversión estimada [COP],Empleos estimados,Emisiones CO2 [Ton/año],Energía [kWh/año],Emisiones CO2 [Ton/días]
0,Jepirachi,Eólico,18.42,La guajira,Uribia,44,44847,2004-04-27,176832.0,30665,7.920600e+10,51,51635.0,64543680.0,141.465753
1,Autog celsia solar yumbo,Solar,9.80,Valle del cauca,Yumbo,76,76892,2017-03-09,47040.0,8157,4.214000e+10,68,13736.0,17169600.0,37.632877
2,Celsia solar bolivar,Solar,8.06,Bolívar,Santa rosa,13,13683,2019-02-01,38688.0,6709,3.465800e+10,56,11297.0,14121120.0,30.950685
3,El paso solar (enel green power),Solar,67.00,Cesar,El paso,20,20250,2019-04-05,321600.0,55769,2.881000e+11,466,93907.0,117384000.0,257.279452
4,Solar castilla ecp,Solar,20.00,Meta,Castilla la nueva,50,50150,2019-10-10,96000.0,16647,8.600000e+10,139,28032.0,35040000.0,76.800000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,Buga 1 parte 2,Solar,5.94,Valle del cauca,"""""",76,76,2022-12-31,28512.0,4944,2.227500e+10,41,8326.0,10406880.0,22.810959
154,Buga 1 parte 1,Solar,3.96,Valle del cauca,"""""",76,76,2022-07-31,19008.0,3296,1.485000e+10,28,5550.0,6937920.0,15.205479
155,Refinería grb,Solar,21.00,Santander,Barrancabermeja,68,68081,2023-12-31,100800.0,17480,7.875000e+10,146,29434.0,36792000.0,80.641096
156,Emsa gd y ag (34 proyectos),Solar,1.90,Meta,Villavicencio,50,50001,2022-05-31,9120.0,1582,8.170000e+09,13,2663.0,3328800.0,7.295890
157,Enelar gd y ag (4 proyectos),Solar,0.11,Arauca,Arauca,81,81001,2022-05-31,528.0,92,4.730000e+08,1,154.0,192720.0,0.421918

## Creación de la tabla solar

In [64]:
solar = df1[df1["Tipo"] == "Solar"].reset_index(drop=True)
solar

,Proyecto,Tipo,Capacidad,Departamento,Municipio,Código Departamento,Código Municipio,Fecha estimada FPO,Energía [kWh/día],Usuarios,Inversión estimada [COP],Empleos estimados,Emisiones CO2 [Ton/año],Energía [kWh/año],Emisiones CO2 [Ton/días]
0,Autog celsia solar yumbo,Solar,9.80,Valle del cauca,Yumbo,76,76892,2017-03-09,47040.0,8157,4.214000e+10,68,13736.0,17169600.0,37.632877
1,Celsia solar bolivar,Solar,8.06,Bolívar,Santa rosa,13,13683,2019-02-01,38688.0,6709,3.465800e+10,56,11297.0,14121120.0,30.950685
2,El paso solar (enel green power),Solar,67.00,Cesar,El paso,20,20250,2019-04-05,321600.0,55769,2.881000e+11,466,93907.0,117384000.0,257.279452
3,Solar castilla ecp,Solar,20.00,Meta,Castilla la nueva,50,50150,2019-10-10,96000.0,16647,8.600000e+10,139,28032.0,35040000.0,76.800000
4,Agpe tecnoempaques de occidente,Solar,0.10,Valle del cauca,Cali,76,76001,2019-12-19,480.0,83,4.300000e+08,1,140.0,175200.0,0.383562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,Parque solar fotovoltaico fundación,Solar,99.00,Magdalena,Fundación,47,47288,2024-06-30,475200.0,82405,3.712500e+11,689,138758.0,173448000.0,380.158904
134,Tuluá,Solar,13.30,Valle del cauca,Tuluá,76,76834,2022-04-30,63840.0,11071,5.719000e+10,93,18641.0,23301600.0,51.071233
135,Refinería grb,Solar,21.00,Santander,Barrancabermeja,68,68081,2023-12-31,100800.0,17480,7.875000e+10,146,29434.0,36792000.0,80.641096
136,Emsa gd y ag (34 proyectos),Solar,1.90,Meta,Villavicencio,50,50001,2022-05-31,9120.0,1582,8.170000e+09,13,2663.0,3328800.0,7.295890
137,Enelar gd y ag (4 proyectos),Solar,0.11,Arauca,Arauca,81,81001,2022-05-31,528.0,92,4.730000e+08,1,154.0,192720.0,0.421918

In [65]:
solar.info()

<class 'pandas.DataFrame'>
RangeIndex: 138 entries, 0 to 137
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Proyecto                  138 non-null    str
 1   Tipo                      138 non-null    str
 2   Capacidad                 138 non-null    float64
 3   Departamento              138 non-null    str
 4   Municipio                 138 non-null    str
 5   Código Departamento       138 non-null    int64
 6   Código Municipio          138 non-null    int64
 7   Fecha estimada FPO        138 non-null    datetime64[us]
 8   Energía [kWh/día]         138 non-null    float64
 9   Usuarios                  138 non-null    int64
 10  Inversión estimada [COP]  138 non-null    float64
 11  Empleos estimados         138 non-null    int64
 12  Emisiones CO2 [Ton/año]   138 non-null    float64
 13  Energía [kWh/año]         138 non-null    float64
 14  Emisiones CO2 [Ton/días]  138 non-null    float64
dtypes: datetime64[us](1), float64(6), int64(4), str(4)
memory usage: 22.3 KB

In [66]:
from IPython.display import FileLink

# 1. Guardas el DataFrame como CSV
solar.to_csv('solar.csv', index=False)

# 2. Creas un enlace de descarga interactivo
FileLink('solar.csv')

c:\Users\USUARIO\OneDrive - Universidad Nacional de Colombia\Documentos\TALENTO_TECH\proyecto_solar\Bootcamp2026-1\Codigo\solar.csv

In [67]:
# Cuenta los registros y lo convierte en una tabla organizada
resumen_tipos_solar = solar['Tipo'].value_counts().reset_index()

# Le cambiamos el nombre a las columnas para que sea más claro
resumen_tipos_solar.columns = ['Tipo de Proyecto', 'Cantidad de Registros']

# Mostramos el resultado
print(resumen_tipos_solar)

  Tipo de Proyecto  Cantidad de Registros
0            Solar                    138

## Limpieza (paso adicional)

In [ ]:
# Manejo de datos faltantes en la columna Municipio => Se observa que hay 5 registros con valor "" en la columna Municipio, lo cual no es un valor nulo pero tampoco es un valor válido para identificar el municipio, por lo que se decide eliminar estos registros ya que representan solo el 0.5% del total de registros y no afectará el análisis general del dataset

In [ ]:
# Se verifica que hay 5 registros con valor "" en la columna Municipio
#df1["Municipio"].value_counts(dropna=False)
print(df1["Municipio"].value_counts(dropna=False).to_string())

Municipio
Uribia                        8
Pereira                       8
Puerto gaitán                 7
Bogotá d.c.                   5
""                            5
Medellín                      4
San josé de cúcuta            4
Chinú                         4
Maicao                        4
Flandes                       4
Sabanalarga                   4
Yumbo                         3
Cali                          3
Cartagena de indias           3
Arauca                        3
Zarzal                        3
Villavicencio                 3
Armero                        3
Malambo                       3
El paso                       2
Castilla la nueva             2
Ibagué                        2
Unguía                        2
Planeta rica                  2
Rionegro                      2
Barrancabermeja               2
Neiva                         2
Montería                      2
Barranquilla                  2
Galapa                        2
Popayán                       2
La dorada                     2
Arjona                        2
Guaduas                       2
Santa rosa                    1
San andrés                    1
Soledad                       1
Espinal                       1
Candelaria                    1
Inírida                       1
Manizales                     1
Tunja                         1
Yopal                         1
San benito abad               1
Armenia                       1
Villanueva                    1
San sebastián de mariquita    1
San luis de sincé             1
Cartago                       1
Zona bananera                 1
Baranoa                       1
Polonuevo                     1
Ciénaga                       1
Yaguará                       1
Cantagallo                    1
Melgar                        1
Andalucía                     1
Manatí                        1
San josé de toluviejo         1
Puerto tejada                 1
Los santos                    1
Girardota                     1
Suesca                        1
Sopó                          1
Madrid                        1
Soacha                        1
Sesquilé                      1
Ginebra                       1
Piedecuesta                   1
Aguachica                     1
La gloria                     1
La esperanza                  1
Chiriguaná                    1
Cimitarra                     1
Santa catalina                1
Puerto nare                   1
Alvarado                      1
Fundación                     1
Tuluá                         1

In [ ]:
#el registro con valor "" en la columna Municipio corresponde a los codigos 23,54 y 76
df1[df1["Municipio"] == '""']

,Proyecto,Tipo,Capacidad,Departamento,Municipio,Código Departamento,Código Municipio,Fecha estimada FPO,Energía [kWh/día],Usuarios,Inversión estimada [COP],Empleos estimados,Emisiones CO2 [Ton/año],Energía [kWh/año],Emisiones CO2 [Ton/días]
134,Aquasol,Solar,1.50,Córdoba,"""""",23,23,2022-10-31,7200.0,1249,5.625000e+09,10,2102.0,2628000.0,5.758904
147,Parque fotovoltaico sunnorte,Solar,35.00,Norte de santander,"""""",54,54,2023-12-31,168000.0,29133,1.312500e+11,244,49056.0,61320000.0,134.400000
152,Parque fotovoltaico montelíbano solar,Solar,9.90,Córdoba,"""""",23,23,2022-10-30,47520.0,8240,3.712500e+10,69,13876.0,17344800.0,38.016438
153,Buga 1 parte 2,Solar,5.94,Valle del cauca,"""""",76,76,2022-12-31,28512.0,4944,2.227500e+10,41,8326.0,10406880.0,22.810959
154,Buga 1 parte 1,Solar,3.96,Valle del cauca,"""""",76,76,2022-07-31,19008.0,3296,1.485000e+10,28,5550.0,6937920.0,15.205479

In [60]:
df1[df1["Código Municipio"] == 23]

,Proyecto,Tipo,Capacidad,Departamento,Municipio,Código Departamento,Código Municipio,Fecha estimada FPO,Energía [kWh/día],Usuarios,Inversión estimada [COP],Empleos estimados,Emisiones CO2 [Ton/año],Energía [kWh/año],Emisiones CO2 [Ton/días]
134,Aquasol,Solar,1.5,Córdoba,"""""",23,23,2022-10-31,7200.0,1249,5.625000e+09,10,2102.0,2628000.0,5.758904
152,Parque fotovoltaico montelíbano solar,Solar,9.9,Córdoba,"""""",23,23,2022-10-30,47520.0,8240,3.712500e+10,69,13876.0,17344800.0,38.016438

In [61]:
df1[df1["Código Municipio"] == 54]

,Proyecto,Tipo,Capacidad,Departamento,Municipio,Código Departamento,Código Municipio,Fecha estimada FPO,Energía [kWh/día],Usuarios,Inversión estimada [COP],Empleos estimados,Emisiones CO2 [Ton/año],Energía [kWh/año],Emisiones CO2 [Ton/días]
147,Parque fotovoltaico sunnorte,Solar,35.0,Norte de santander,"""""",54,54,2023-12-31,168000.0,29133,1.312500e+11,244,49056.0,61320000.0,134.4

In [62]:
df1[df1["Código Municipio"] == 76]

,Proyecto,Tipo,Capacidad,Departamento,Municipio,Código Departamento,Código Municipio,Fecha estimada FPO,Energía [kWh/día],Usuarios,Inversión estimada [COP],Empleos estimados,Emisiones CO2 [Ton/año],Energía [kWh/año],Emisiones CO2 [Ton/días]
153,Buga 1 parte 2,Solar,5.94,Valle del cauca,"""""",76,76,2022-12-31,28512.0,4944,2.227500e+10,41,8326.0,10406880.0,22.810959
154,Buga 1 parte 1,Solar,3.96,Valle del cauca,"""""",76,76,2022-07-31,19008.0,3296,1.485000e+10,28,5550.0,6937920.0,15.205479

In [ ]:
#Se eliminan los registros con valor "" en la columna Municipio ya que no hay suficiente infromación apra identificar a que municipios corresponden (el codigo de municipio debe ser de 5 dígitos y también está malo) y solo representan 5 registros de un total de 1000, por lo que no afectará el análisis general del dataset
df1 = df1[df1["Municipio"] != '""'].reset_index(drop=True)