In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('C:/Users/Alejandro/OneDrive/Documents/GitHub/Bootcamp2026-1/Documentos/MES_1225.xlsx')

In [49]:
df.head(20)

,The Monthly electricity data explorer and the main highlights are available here: https://www.iea.org/reports/monthly-electricity-statistics-overview,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,False,NaN,NaN,NaN,NaN,NaN
2,"In particular, external dissemination of any I...",NaN,NaN,NaN,NaN,NaN
3,Please contact us at stats@iea.org if you have...,NaN,NaN,NaN,NaN,NaN
4,Last update:,15 March 2026,NaN,NaN,NaN,NaN
5,"This notice, and any copyright or sourcing sta...",NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN
7,Country,Time,Balance,Product,Value,Unit
8,Australia,December 2025,Net Electricity Production,Electricity,23360.4375,GWh
9,Australia,December 2025,Net Electricity Production,Hydro,932.8479,GWh
10,Australia,December 2025,Net Electricity Production,Total Combustible Fuels,12210.7489,GWh
11,Australia,December 2025,Net Electricity Production,"Coal, Peat and Manufactured Gases",8782.6749,GWh
12,Australia,December 2025,Net Electricity Production,Oil and Petroleum Products,293.4672,GWh
13,Australia,December 2025,Net Electricity Production,Natural Gas,2948.0199,GWh
14,Australia,December 2025,Net Electricity Production,Combustible Renewables,186.5869,GWh
15,Australia,December 2025,Net Electricity Production,Solar,6688.7891,GWh
16,Australia,December 2025,Net Electricity Production,"Total Renewables (Hydro, Geo, Solar, Wind, Other)",11336.2756,GWh
17,Australia,December 2025,Used for pumped storage,Electricity,80.4632,GWh
18,Australia,December 2025,Distribution Losses,Electricity,1135.38,GWh
19,Australia,December 2025,Final Consumption (Calculated),Electricity,22144.5943,GWh

In [50]:
df = df.drop(df.index[0:7], axis = 0)
df.reset_index(drop = True)
df

,The Monthly electricity data explorer and the main highlights are available here: https://www.iea.org/reports/monthly-electricity-statistics-overview,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
7,Country,Time,Balance,Product,Value,Unit
8,Australia,December 2025,Net Electricity Production,Electricity,23360.4375,GWh
9,Australia,December 2025,Net Electricity Production,Hydro,932.8479,GWh
10,Australia,December 2025,Net Electricity Production,Total Combustible Fuels,12210.7489,GWh
11,Australia,December 2025,Net Electricity Production,"Coal, Peat and Manufactured Gases",8782.6749,GWh
...,...,...,...,...,...,...
158181,IEA Total,January 2010,Total Exports,Electricity,32372.583,GWh
158182,IEA Total,January 2010,Used for pumped storage,Electricity,6869.253,GWh
158183,IEA Total,January 2010,Distribution Losses,Electricity,62000.733,GWh
158184,IEA Total,January 2010,Final Consumption (Calculated),Electricity,877213.615,GWh
158185,IEA Total,January 2010,Net Electricity Production,Wind,21659.612,GWh

In [ ]:
df.columns

,The Monthly electricity data explorer and the main highlights are available here: https://www.iea.org/reports/monthly-electricity-statistics-overview,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
7,Country,Time,Balance,Product,Value,Unit
8,Australia,December 2025,Net Electricity Production,Electricity,23360.4375,GWh
9,Australia,December 2025,Net Electricity Production,Hydro,932.8479,GWh
10,Australia,December 2025,Net Electricity Production,Total Combustible Fuels,12210.7489,GWh
11,Australia,December 2025,Net Electricity Production,"Coal, Peat and Manufactured Gases",8782.6749,GWh
...,...,...,...,...,...,...
158181,IEA Total,January 2010,Total Exports,Electricity,32372.583,GWh
158182,IEA Total,January 2010,Used for pumped storage,Electricity,6869.253,GWh
158183,IEA Total,January 2010,Distribution Losses,Electricity,62000.733,GWh
158184,IEA Total,January 2010,Final Consumption (Calculated),Electricity,877213.615,GWh
158185,IEA Total,January 2010,Net Electricity Production,Wind,21659.612,GWh

In [53]:
df.columns = df.iloc[0]
df.drop(7, inplace=True)

In [54]:
df.reset_index(drop = True)
df.columns.name = None

In [55]:
nulos = df.isnull()
nulos = df[nulos['Value'] == True]
nulos

,Country,Time,Balance,Product,Value,Unit
102,Costa Rica,December 2025,Remarks,Data is estimated for this month,NaN,GWh
249,Iceland,December 2025,Remarks,Data is estimated for this month,NaN,GWh
292,Japan,December 2025,Remarks,Data is estimated for this month,NaN,GWh
702,Argentina,December 2025,Remarks,Data is estimated for this month,NaN,GWh
915,Costa Rica,November 2025,Remarks,Data is estimated for this month,NaN,GWh
1062,Iceland,November 2025,Remarks,Data is estimated for this month,NaN,GWh
1105,Japan,November 2025,Remarks,Data is estimated for this month,NaN,GWh
1514,Argentina,November 2025,Remarks,Data is estimated for this month,NaN,GWh
1726,Costa Rica,October 2025,Remarks,Data is estimated for this month,NaN,GWh
1874,Iceland,October 2025,Remarks,Data is estimated for this month,NaN,GWh
2326,Argentina,October 2025,Remarks,Data is estimated for this month,NaN,GWh
2539,Costa Rica,September 2025,Remarks,Data is estimated for this month,NaN,GWh
2687,Iceland,September 2025,Remarks,Data is estimated for this month,NaN,GWh
3140,Argentina,September 2025,Remarks,Data is estimated for this month,NaN,GWh
3354,Costa Rica,August 2025,Remarks,Data is estimated for this month,NaN,GWh
3502,Iceland,August 2025,Remarks,Data is estimated for this month,NaN,GWh
3953,Argentina,August 2025,Remarks,Data is estimated for this month,NaN,GWh
4167,Costa Rica,July 2025,Remarks,Data is estimated for this month,NaN,GWh
4315,Iceland,July 2025,Remarks,Data is estimated for this month,NaN,GWh
4982,Costa Rica,June 2025,Remarks,Data is estimated for this month,NaN,GWh
5130,Iceland,June 2025,Remarks,Data is estimated for this month,NaN,GWh
5794,Costa Rica,May 2025,Remarks,Data is estimated for this month,NaN,GWh
5943,Iceland,May 2025,Remarks,Data is estimated for this month,NaN,GWh
6396,Argentina,May 2025,Remarks,Data is estimated for this month,NaN,GWh
6608,Costa Rica,April 2025,Remarks,Data is estimated for this month,NaN,GWh
6757,Iceland,April 2025,Remarks,Data is estimated for this month,NaN,GWh
7211,Argentina,April 2025,Remarks,Data is estimated for this month,NaN,GWh
7424,Costa Rica,March 2025,Remarks,Data is estimated for this month,NaN,GWh
7573,Iceland,March 2025,Remarks,Data is estimated for this month,NaN,GWh
8240,Costa Rica,February 2025,Remarks,Data is estimated for this month,NaN,GWh
8389,Iceland,February 2025,Remarks,Data is estimated for this month,NaN,GWh
9055,Costa Rica,January 2025,Remarks,Data is estimated for this month,NaN,GWh
9204,Iceland,January 2025,Remarks,Data is estimated for this month,NaN,GWh
9869,Costa Rica,December 2024,Remarks,Data is estimated for this month,NaN,GWh
10017,Iceland,December 2024,Remarks,Data is estimated for this month,NaN,GWh
10684,Costa Rica,November 2024,Remarks,Data is estimated for this month,NaN,GWh
10832,Iceland,November 2024,Remarks,Data is estimated for this month,NaN,GWh
11500,Costa Rica,October 2024,Remarks,Data is estimated for this month,NaN,GWh
12315,Costa Rica,September 2024,Remarks,Data is estimated for this month,NaN,GWh
13132,Costa Rica,August 2024,Remarks,Data is estimated for this month,NaN,GWh
13948,Costa Rica,July 2024,Remarks,Data is estimated for this month,NaN,GWh
14764,Costa Rica,June 2024,Remarks,Data is estimated for this month,NaN,GWh
15578,Costa Rica,May 2024,Remarks,Data is estimated for this month,NaN,GWh
16392,Costa Rica,April 2024,Remarks,Data is estimated for this month,NaN,GWh
17210,Costa Rica,March 2024,Remarks,Data is estimated for this month,NaN,GWh
18025,Costa Rica,February 2024,Remarks,Data is estimated for this month,NaN,GWh
18838,Costa Rica,January 2024,Remarks,Data is estimated for this month,NaN,GWh
19653,Costa Rica,December 2023,Remarks,Data is estimated for this month,NaN,GWh
20467,Costa Rica,November 2023,Remarks,Data is estimated for this month,NaN,GWh
21284,Costa Rica,October 2023,Remarks,Data is estimated for this month,NaN,GWh
22101,Costa Rica,September 2023,Remarks,Data is estimated for this month,NaN,GWh
22917,Costa Rica,August 2023,Remarks,Data is estimated for this month,NaN,GWh
23734,Costa Rica,July 2023,Remarks,Data is estimated for this month,NaN,GWh
24552,Costa Rica,June 2023,Remarks,Data is estimated for this month,NaN,GWh
25369,Costa Rica,May 2023,Remarks,Data is estimated for this month,NaN,GWh
26186,Costa Rica,April 2023,Remarks,Data is estimated for this month,NaN,GWh
27006,Costa Rica,March 2023,Remarks,Data is estimated for this month,NaN,GWh
27825,Costa Rica,February 2023,Remarks,Data is estimated for this month,NaN,GWh
28644,Costa Rica,January 2023,Remarks,Data is estimated for this month,NaN,GWh

In [56]:
df.dropna(inplace=True)

In [57]:
df.isna().sum()

Country    0
Time       0
Balance    0
Product    0
Value      0
Unit       0
dtype: int64

In [58]:
colombia = df[df['Country'] == 'Colombia']
colombia.reset_index(drop = True)

,Country,Time,Balance,Product,Value,Unit
0,Colombia,December 2025,Net Electricity Production,Electricity,7794.9781,GWh
1,Colombia,December 2025,Net Electricity Production,Hydro,5530.6545,GWh
2,Colombia,December 2025,Net Electricity Production,Total Combustible Fuels,1764.6682,GWh
3,Colombia,December 2025,Net Electricity Production,"Coal, Peat and Manufactured Gases",483.3555,GWh
4,Colombia,December 2025,Net Electricity Production,Oil and Petroleum Products,287.5943,GWh
...,...,...,...,...,...,...
2341,Colombia,January 2014,Total Imports,Electricity,0.021,GWh
2342,Colombia,January 2014,Total Exports,Electricity,146.888,GWh
2343,Colombia,January 2014,Distribution Losses,Electricity,536.164,GWh
2344,Colombia,January 2014,Final Consumption (Calculated),Electricity,5019.684,GWh
2345,Colombia,January 2014,Net Electricity Production,Wind,5.648,GWh

In [ ]:
productos = colombia['Product'].value_counts()
productos

np.int64(2346)

In [63]:
df.columns

Index(['Country', 'Time', 'Balance', 'Product', 'Value', 'Unit'], dtype='object')