In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel('MES_1225.xlsx')

In [5]:
df.head(20)

,The Monthly electricity data explorer and the main highlights are available here: https://www.iea.org/reports/monthly-electricity-statistics-overview,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,NaN,NaN,NaN,NaN
1,False,NaN,NaN,NaN,NaN,NaN
2,"In particular, external dissemination of any I...",NaN,NaN,NaN,NaN,NaN
3,Please contact us at stats@iea.org if you have...,NaN,NaN,NaN,NaN,NaN
4,Last update:,NaN,15 March 2026,NaN,NaN,NaN
5,"This notice, and any copyright or sourcing sta...",NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN
7,Country,Balance,Time,Product,Value,Unit
8,Australia,Net Electricity Production,December 2025,Electricity,23360.4375,GWh
9,Australia,Net Electricity Production,December 2025,Hydro,932.8479,GWh
10,Australia,Net Electricity Production,December 2025,Total Combustible Fuels,12210.7489,GWh
11,Australia,Net Electricity Production,December 2025,"Coal, Peat and Manufactured Gases",8782.6749,GWh
12,Australia,Net Electricity Production,December 2025,Oil and Petroleum Products,293.4672,GWh
13,Australia,Net Electricity Production,December 2025,Natural Gas,2948.0199,GWh
14,Australia,Net Electricity Production,December 2025,Combustible Renewables,186.5869,GWh
15,Australia,Net Electricity Production,December 2025,Solar,6688.7891,GWh
16,Australia,Net Electricity Production,December 2025,"Total Renewables (Hydro, Geo, Solar, Wind, Other)",11336.2756,GWh
17,Australia,Used for pumped storage,December 2025,Electricity,80.4632,GWh
18,Australia,Distribution Losses,December 2025,Electricity,1135.38,GWh
19,Australia,Final Consumption (Calculated),December 2025,Electricity,22144.5943,GWh

In [6]:
df = df.drop(df.index[0:7], axis = 0)
df.reset_index(drop = True)
df

,The Monthly electricity data explorer and the main highlights are available here: https://www.iea.org/reports/monthly-electricity-statistics-overview,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
7,Country,Balance,Time,Product,Value,Unit
8,Australia,Net Electricity Production,December 2025,Electricity,23360.4375,GWh
9,Australia,Net Electricity Production,December 2025,Hydro,932.8479,GWh
10,Australia,Net Electricity Production,December 2025,Total Combustible Fuels,12210.7489,GWh
11,Australia,Net Electricity Production,December 2025,"Coal, Peat and Manufactured Gases",8782.6749,GWh
...,...,...,...,...,...,...
158181,IEA Total,Total Exports,January 2010,Electricity,32372.583,GWh
158182,IEA Total,Used for pumped storage,January 2010,Electricity,6869.253,GWh
158183,IEA Total,Distribution Losses,January 2010,Electricity,62000.733,GWh
158184,IEA Total,Final Consumption (Calculated),January 2010,Electricity,877213.615,GWh
158185,IEA Total,Net Electricity Production,January 2010,Wind,21659.612,GWh

In [17]:
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 158119 entries, 8 to 158185
Data columns (total 6 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Country  158119 non-null  object
 1   Balance  158119 non-null  object
 2   Time     158119 non-null  object
 3   Product  158119 non-null  object
 4   Value    158119 non-null  object
 5   Unit     158119 non-null  object
dtypes: object(6)
memory usage: 8.4+ MB

In [8]:
df.columns = df.iloc[0]
df.drop(7, inplace=True)

In [9]:
df.reset_index(drop = True)
df.columns.name = None

In [10]:
nulos = df.isnull()
nulos = df[nulos['Value'] == True]
nulos

,Country,Balance,Time,Product,Value,Unit
102,Costa Rica,Remarks,December 2025,Data is estimated for this month,NaN,GWh
249,Iceland,Remarks,December 2025,Data is estimated for this month,NaN,GWh
292,Japan,Remarks,December 2025,Data is estimated for this month,NaN,GWh
702,Argentina,Remarks,December 2025,Data is estimated for this month,NaN,GWh
915,Costa Rica,Remarks,November 2025,Data is estimated for this month,NaN,GWh
1062,Iceland,Remarks,November 2025,Data is estimated for this month,NaN,GWh
1105,Japan,Remarks,November 2025,Data is estimated for this month,NaN,GWh
1514,Argentina,Remarks,November 2025,Data is estimated for this month,NaN,GWh
1726,Costa Rica,Remarks,October 2025,Data is estimated for this month,NaN,GWh
1874,Iceland,Remarks,October 2025,Data is estimated for this month,NaN,GWh
2326,Argentina,Remarks,October 2025,Data is estimated for this month,NaN,GWh
2539,Costa Rica,Remarks,September 2025,Data is estimated for this month,NaN,GWh
2687,Iceland,Remarks,September 2025,Data is estimated for this month,NaN,GWh
3140,Argentina,Remarks,September 2025,Data is estimated for this month,NaN,GWh
3354,Costa Rica,Remarks,August 2025,Data is estimated for this month,NaN,GWh
3502,Iceland,Remarks,August 2025,Data is estimated for this month,NaN,GWh
3953,Argentina,Remarks,August 2025,Data is estimated for this month,NaN,GWh
4167,Costa Rica,Remarks,July 2025,Data is estimated for this month,NaN,GWh
4315,Iceland,Remarks,July 2025,Data is estimated for this month,NaN,GWh
4982,Costa Rica,Remarks,June 2025,Data is estimated for this month,NaN,GWh
5130,Iceland,Remarks,June 2025,Data is estimated for this month,NaN,GWh
5794,Costa Rica,Remarks,May 2025,Data is estimated for this month,NaN,GWh
5943,Iceland,Remarks,May 2025,Data is estimated for this month,NaN,GWh
6396,Argentina,Remarks,May 2025,Data is estimated for this month,NaN,GWh
6608,Costa Rica,Remarks,April 2025,Data is estimated for this month,NaN,GWh
6757,Iceland,Remarks,April 2025,Data is estimated for this month,NaN,GWh
7211,Argentina,Remarks,April 2025,Data is estimated for this month,NaN,GWh
7424,Costa Rica,Remarks,March 2025,Data is estimated for this month,NaN,GWh
7573,Iceland,Remarks,March 2025,Data is estimated for this month,NaN,GWh
8240,Costa Rica,Remarks,February 2025,Data is estimated for this month,NaN,GWh
8389,Iceland,Remarks,February 2025,Data is estimated for this month,NaN,GWh
9055,Costa Rica,Remarks,January 2025,Data is estimated for this month,NaN,GWh
9204,Iceland,Remarks,January 2025,Data is estimated for this month,NaN,GWh
9869,Costa Rica,Remarks,December 2024,Data is estimated for this month,NaN,GWh
10017,Iceland,Remarks,December 2024,Data is estimated for this month,NaN,GWh
10684,Costa Rica,Remarks,November 2024,Data is estimated for this month,NaN,GWh
10832,Iceland,Remarks,November 2024,Data is estimated for this month,NaN,GWh
11500,Costa Rica,Remarks,October 2024,Data is estimated for this month,NaN,GWh
12315,Costa Rica,Remarks,September 2024,Data is estimated for this month,NaN,GWh
13132,Costa Rica,Remarks,August 2024,Data is estimated for this month,NaN,GWh
13948,Costa Rica,Remarks,July 2024,Data is estimated for this month,NaN,GWh
14764,Costa Rica,Remarks,June 2024,Data is estimated for this month,NaN,GWh
15578,Costa Rica,Remarks,May 2024,Data is estimated for this month,NaN,GWh
16392,Costa Rica,Remarks,April 2024,Data is estimated for this month,NaN,GWh
17210,Costa Rica,Remarks,March 2024,Data is estimated for this month,NaN,GWh
18025,Costa Rica,Remarks,February 2024,Data is estimated for this month,NaN,GWh
18838,Costa Rica,Remarks,January 2024,Data is estimated for this month,NaN,GWh
19653,Costa Rica,Remarks,December 2023,Data is estimated for this month,NaN,GWh
20467,Costa Rica,Remarks,November 2023,Data is estimated for this month,NaN,GWh
21284,Costa Rica,Remarks,October 2023,Data is estimated for this month,NaN,GWh
22101,Costa Rica,Remarks,September 2023,Data is estimated for this month,NaN,GWh
22917,Costa Rica,Remarks,August 2023,Data is estimated for this month,NaN,GWh
23734,Costa Rica,Remarks,July 2023,Data is estimated for this month,NaN,GWh
24552,Costa Rica,Remarks,June 2023,Data is estimated for this month,NaN,GWh
25369,Costa Rica,Remarks,May 2023,Data is estimated for this month,NaN,GWh
26186,Costa Rica,Remarks,April 2023,Data is estimated for this month,NaN,GWh
27006,Costa Rica,Remarks,March 2023,Data is estimated for this month,NaN,GWh
27825,Costa Rica,Remarks,February 2023,Data is estimated for this month,NaN,GWh
28644,Costa Rica,Remarks,January 2023,Data is estimated for this month,NaN,GWh

In [11]:
df.dropna(inplace=True)

In [12]:
df.isna().sum()

Country    0
Balance    0
Time       0
Product    0
Value      0
Unit       0
dtype: int64

In [26]:
df['Time'] = pd.to_datetime(df['Time'])
# Extraer el número del mes (1 al 12)

df['Month'] = df['Time'].dt.month
# Extraer el año (ej. 2026)
df['Year'] = df['Time'].dt.year

colombia = df[df['Country'] == 'Colombia']
colombia.reset_index(drop = True)

,Country,Balance,Time,Product,Value,Unit,Month,Year
0,Colombia,Net Electricity Production,2025-12-01,Electricity,7794.9781,GWh,12,2025
1,Colombia,Net Electricity Production,2025-12-01,Hydro,5530.6545,GWh,12,2025
2,Colombia,Net Electricity Production,2025-12-01,Total Combustible Fuels,1764.6682,GWh,12,2025
3,Colombia,Net Electricity Production,2025-12-01,"Coal, Peat and Manufactured Gases",483.3555,GWh,12,2025
4,Colombia,Net Electricity Production,2025-12-01,Oil and Petroleum Products,287.5943,GWh,12,2025
...,...,...,...,...,...,...,...,...
2341,Colombia,Total Imports,2014-01-01,Electricity,0.021,GWh,1,2014
2342,Colombia,Total Exports,2014-01-01,Electricity,146.888,GWh,1,2014
2343,Colombia,Distribution Losses,2014-01-01,Electricity,536.164,GWh,1,2014
2344,Colombia,Final Consumption (Calculated),2014-01-01,Electricity,5019.684,GWh,1,2014
2345,Colombia,Net Electricity Production,2014-01-01,Wind,5.648,GWh,1,2014

In [29]:
from IPython.display import FileLink

# 1. Guardas el DataFrame como CSV
colombia.to_csv('colombia.csv', index=False)

# 2. Creas un enlace de descarga interactivo
FileLink('colombia.csv')

c:\Users\Laboratorio\Documents\proyecto\colombia.csv

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 158119 entries, 8 to 158185
Data columns (total 6 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   Country  158119 non-null  object
 1   Balance  158119 non-null  object
 2   Time     158119 non-null  datetime64[ns]
 3   Product  158119 non-null  object
 4   Value    158119 non-null  object
 5   Unit     158119 non-null  object
dtypes: datetime64[ns](1), object(5)
memory usage: 8.4+ MB

In [14]:
productos = colombia['Product'].value_counts()
productos

Product
Electricity                                          768
Hydro                                                144
Total Combustible Fuels                              144
Coal, Peat and Manufactured Gases                    144
Oil and Petroleum Products                           144
Natural Gas                                          144
Combustible Renewables                               144
Solar                                                144
Total Renewables (Hydro, Geo, Solar, Wind, Other)    144
Wind                                                 140
Not Specified                                         92
Other Combustible Non-Renewables                      50
Nuclear                                               48
Geothermal                                            48
Other Renewables                                      48
Name: count, dtype: int64

In [ ]:

# Cuenta los registros y lo convierte en una tabla organizada
resumen_tipos = colombia['Product'].value_counts().reset_index()

# Opcional: Le cambiamos el nombre a las columnas para que sea más claro
resumen_tipos.columns = ['Tipo de Proyecto', 'Cantidad de Registros']

# Mostramos el resultado
print(resumen_tipos)

                                     Tipo de Proyecto  Cantidad de Registros
0                                         Electricity                    768
1                                               Hydro                    144
2                             Total Combustible Fuels                    144
3                   Coal, Peat and Manufactured Gases                    144
4                          Oil and Petroleum Products                    144
5                                         Natural Gas                    144
6                              Combustible Renewables                    144
7                                               Solar                    144
8   Total Renewables (Hydro, Geo, Solar, Wind, Other)                    144
9                                                Wind                    140
10                                      Not Specified                     92
11                   Other Combustible Non-Renewables                     50
12                                            Nuclear                     48
13                                         Geothermal                     48
14                                   Other Renewables                     48

In [27]:
# Cuenta los registros y lo convierte en una tabla organizada
resumen_años = colombia['Year'].value_counts().reset_index()

# Opcional: Le cambiamos el nombre a las columnas para que sea más claro
resumen_años.columns = ['Año', 'Cantidad de Registros por año']

# Mostramos el resultado
print(resumen_años)

     Año  Cantidad de Registros por año
0   2021                            240
1   2020                            240
2   2019                            240
3   2018                            240
4   2022                            182
5   2024                            180
6   2023                            180
7   2025                            176
8   2016                            168
9   2015                            168
10  2014                            168
11  2017                            164

In [28]:
# Cuenta los registros y lo convierte en una tabla organizada
resumen_años = colombia['Month'].value_counts().reset_index()

# Opcional: Le cambiamos el nombre a las columnas para que sea más claro
resumen_años.columns = ['Mes', 'Cantidad de Registros por mes']

# Mostramos el resultado
print(resumen_años)

    Mes  Cantidad de Registros por mes
0     8                            196
1     6                            196
2     5                            196
3     4                            196
4     2                            196
5     1                            196
6    12                            195
7    11                            195
8    10                            195
9     9                            195
10    7                            195
11    3                            195