In [126]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('colombia.csv')

## Revisión general

In [127]:
df.info() 
#No hay valores nulos, pero hay 2 columnas con tipo de dato object, lo que puede indicar que hay datos no numéricos en esas columnas. 
#Es importante revisar esas columnas para asegurarse de que los datos sean consistentes y puedan ser utilizados para análisis posteriores.

<class 'pandas.DataFrame'>
RangeIndex: 2346 entries, 0 to 2345
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  2346 non-null   str
 1   Time     2346 non-null   str
 2   Balance  2346 non-null   str
 3   Product  2346 non-null   str
 4   Value    2346 non-null   float64
 5   Unit     2346 non-null   str
 6   Month    2346 non-null   int64
 7   Year     2346 non-null   int64
dtypes: float64(1), int64(2), str(5)
memory usage: 146.8 KB

In [128]:
df.head()

,Country,Time,Balance,Product,Value,Unit,Month,Year
0,Colombia,2025-12-01,Net Electricity Production,Electricity,7794.9781,GWh,12,2025
1,Colombia,2025-12-01,Net Electricity Production,Hydro,5530.6545,GWh,12,2025
2,Colombia,2025-12-01,Net Electricity Production,Total Combustible Fuels,1764.6682,GWh,12,2025
3,Colombia,2025-12-01,Net Electricity Production,"Coal, Peat and Manufactured Gases",483.3555,GWh,12,2025
4,Colombia,2025-12-01,Net Electricity Production,Oil and Petroleum Products,287.5943,GWh,12,2025

In [129]:
# Cambio de tipo de dato de la columna 'Time' a formato datetime para facilitar el análisis temporal.
df['Time'] = pd.to_datetime(df['Time'])

In [130]:
#revisando
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2346 entries, 0 to 2345
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  2346 non-null   str
 1   Time     2346 non-null   datetime64[us]
 2   Balance  2346 non-null   str
 3   Product  2346 non-null   str
 4   Value    2346 non-null   float64
 5   Unit     2346 non-null   str
 6   Month    2346 non-null   int64
 7   Year     2346 non-null   int64
dtypes: datetime64[us](1), float64(1), int64(2), str(4)
memory usage: 146.8 KB

## ✅ 1. Crear la clasificación

In [157]:
clasificacion = {
    "Hydro": "Renovable",
    "Solar": "Renovable",
    "Wind": "Renovable",
    "Geothermal": "Renovable",
    "Other Renewables": "Renovable",
    "Combustible Renewables": "Renovable",
    "Total Renewables (Hydro, Geo, Solar, Wind, Other)": "Renovable",

    "Coal, Peat and Manufactured Gases": "No Renovable",
    "Oil and Petroleum Products": "No Renovable",
    "Natural Gas": "No Renovable",
    "Other Combustible Non-Renewables": "No Renovable",
    "Total Combustible Fuels": "No Renovable",
    "Nuclear": "No Renovable",

    "Electricity": "No clasificado",
    "Not Specified": "No clasificado"
}

## ✅ 2. Aplicar la clasificación al dataframe

In [159]:
df_filtrado["Product"] = df_filtrado["Product"].map(clasificacion)

# Eliminar registros con NaN en la columna Product después de la clasificación
df_filtrado = df_filtrado.dropna(subset=["Product"])

In [131]:
df.head()

,Country,Time,Balance,Product,Value,Unit,Month,Year
0,Colombia,2025-12-01,Net Electricity Production,Electricity,7794.9781,GWh,12,2025
1,Colombia,2025-12-01,Net Electricity Production,Hydro,5530.6545,GWh,12,2025
2,Colombia,2025-12-01,Net Electricity Production,Total Combustible Fuels,1764.6682,GWh,12,2025
3,Colombia,2025-12-01,Net Electricity Production,"Coal, Peat and Manufactured Gases",483.3555,GWh,12,2025
4,Colombia,2025-12-01,Net Electricity Production,Oil and Petroleum Products,287.5943,GWh,12,2025

## Elimina totales para no duplicar datos:

In [155]:
#En el dataset aparecen filas con valores como "Total Imports", "Total Exports", "Distribution Losses" y "Final Consumption (Calculated)" en la columna "Balance".
#estas filas no representan un tipo específico de energía, sino que son totales o cálculos relacionados con el balance energético.
values_to_remove_balance = ["Total Imports", "Total Exports", "Distribution Losses", "Final Consumption (Calculated)", "Used for pumped storage"]

#También hay totales en la columna "Product" que duplican datos
values_to_remove_product = ["Total Combustible Fuels", "Total Renewables (Hydro, Geo, Solar, Wind, Other)"]

df_filtrado = df[
    ~df["Balance"].isin(values_to_remove_balance) &
    ~df["Product"].isin(values_to_remove_product)
]

In [104]:
df_filtrado.info()

<class 'pandas.DataFrame'>
Index: 1342 entries, 0 to 2345
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Country  1342 non-null   str
 1   Time     1342 non-null   datetime64[us]
 2   Balance  1342 non-null   str
 3   Product  1342 non-null   str
 4   Value    1342 non-null   float64
 5   Unit     1342 non-null   str
 6   Month    1342 non-null   int64
 7   Year     1342 non-null   int64
dtypes: datetime64[us](1), float64(1), int64(2), str(4)
memory usage: 94.4 KB

In [154]:
df_filtrado.head(10)

,Country,Time,Balance,Product,Value,Unit,Month,Year
1,Colombia,2025-12-01,Net Electricity Production,Renovable,5530.6545,GWh,12,2025
3,Colombia,2025-12-01,Net Electricity Production,No Renovable,483.3555,GWh,12,2025
4,Colombia,2025-12-01,Net Electricity Production,No Renovable,287.5943,GWh,12,2025
5,Colombia,2025-12-01,Net Electricity Production,No Renovable,764.0410,GWh,12,2025
6,Colombia,2025-12-01,Net Electricity Production,Renovable,229.6775,GWh,12,2025
7,Colombia,2025-12-01,Net Electricity Production,Renovable,479.8602,GWh,12,2025
13,Colombia,2025-12-01,Net Electricity Production,Renovable,19.7951,GWh,12,2025
15,Colombia,2025-11-01,Net Electricity Production,Renovable,5373.6740,GWh,11,2025
17,Colombia,2025-11-01,Net Electricity Production,No Renovable,271.8022,GWh,11,2025
18,Colombia,2025-11-01,Net Electricity Production,No Renovable,264.3055,GWh,11,2025

In [171]:
#Eliminar Nan
df_filtrado['Product'].unique()

<StringArray>
['No clasificado', 'Renovable', 'No Renovable']
Length: 3, dtype: str

In [ ]:
print("Valores únicos en Product DESPUÉS de clasificación:")
productos_despues = df_filtrado["Product"].unique()
print(productos_despues)
print(f"\n¿Hay NaN? {df_filtrado['Product'].isna().any()}")
print(f"Número de NaN: {df_filtrado['Product'].isna().sum()}")
print(f"\nTotal de registros: {len(df_filtrado)}")

Valores únicos en Product DESPUÉS de clasificación:
<StringArray>
['No clasificado', 'Renovable', 'No Renovable']
Length: 3, dtype: str

¿Hay NaN? False
Número de NaN: 0

Total de registros: 1434

## ✅ 3. Crear tabla agregada

In [169]:
# Filtrar solo Renovable y No Renovable
df_final = df_filtrado[df_filtrado["Product"] != "No clasificado"]

tabla_resumen = df_final.groupby("Product")["Value"].sum().reset_index()
tabla_resumen["Value"] = tabla_resumen["Value"].astype(int)
# Agregar columna Unit
tabla_resumen["Unit"] = "GWh"
tabla_resumen = tabla_resumen[["Product", "Value", "Unit"]]

## ✅ 4. Ver resultado

In [167]:
tabla_resumen

        Product   Value Unit
0  No Renovable  270068  GWh
1     Renovable  688661  GWh

## ✅ 5. Gráfico de torta

In [173]:
# Guardar tabla_resumen como CSV
tabla_resumen.to_csv('tabla_resumen.csv', index=False)
print("✅ tabla_resumen guardada como 'tabla_resumen.csv'")

# Guardar df_filtrado como CSV
df_final.to_csv('datos_final.csv', index=False)
print("✅ df_final guardado como 'datos_final.csv'")

# Verificar que los archivos se crearon
import os
print(f"\nArchivos en la carpeta Codigo:")
for file in os.listdir('.'):
    if file.endswith('.csv'):
        print(f"- {file}")

✅ tabla_resumen guardada como 'tabla_resumen.csv'
✅ df_final guardado como 'datos_final.csv'

Archivos en la carpeta Codigo:
- colombia.csv
- datos_filtrados.csv
- datos_final.csv
- tabla_resumen.csv